"""
The Artist (Job B) - v31.0 Gold Master
The Renderer for Sovereign Sentinel.
STRICT RULE: NO NETWORK CALLS (No requests, No yfinance).
Reads data/live_state.json and generates index.html.
"""

import json
import os
import sys
from datetime import datetime
from jinja2 import Template

# ==============================================================================
# CONFIGURATION
# ==============================================================================
STATE_FILE = "live_state.json"
TEMPLATE_FILE = "templates/base.html"
OUTPUT_FILE = "index.html"

def load_state():
    """Reads the Live State snapshot generated by Job A."""
    if not os.path.exists(STATE_FILE):
        print(f"[ARTIST] [ERROR] State file {STATE_FILE} not found. please run the Auditor (Job A) first.")
        return None
        
    try:
        with open(STATE_FILE, 'r') as f:
            return json.load(f)
    except Exception as e:
        print(f"[ARTIST] [ERROR] Could not read state file: {e}")
        return None

def render():
    print(f"Starting The Artist (Job B) [v31.0]... ({datetime.now().strftime('%H:%M:%S')})")
    
    # 1. Load Data
    state = load_state()
    if not state:
        sys.exit(1)
        
    meta = state.get('meta', {})
    metrics = state.get('metrics', {})
    holdings = state.get('holdings', [])
    sniper_data = state.get('sniper_data', [])
    account = state.get('account', {})
    
    print(f"      [DATA] Snapshot Timestamp: {meta.get('timestamp', 'N/A')}")
    print(f"      [DATA] Processing {len(holdings)} holdings and {len(sniper_data)} targets.")

    # 2. Reconstruct Metrics for Template
    # The Template uses these specific variable names
    total_wealth = metrics.get('total_wealth_gbp', 0.0)
    cash_dry = metrics.get('cash_free', 0.0)
    total_return = metrics.get('return_ppl', 0.0)
    invested = metrics.get('invested', 0.0)
    
    return_pct = 0.0
    if invested > 0:
        return_pct = (total_return / invested) * 100

    # 3. Heatmap Data (Custom Formatted for ApexCharts)
    heatmap_series = []
    for h in holdings:
        val = h.get('value_gbp', 0.0)
        pnl = h.get('ppl_gbp', 0.0)
        invested_val = val - pnl
        pct = (pnl / invested_val) if invested_val > 0 else 0.0
        
        heatmap_series.append({
            'x': h.get('ticker', 'N/A').split('_')[0].split('.')[0],
            'y': val,
            'val_pct': pct,
            'company_name': h.get('ticker', 'N/A'),
            'shares_held': f"{h.get('qty', 0):,.4f}",
            'formatted_value': f"£{val:,.2f}",
            'formatted_pl_gbp': f"{'+' if pnl >= 0 else ''}£{pnl:,.2f}",
            'formatted_pl_pct': f"({pct*100:+.1f}%)",
            'price_avg': f"{h.get('price_avg', 0):,.2f}",
            'price_cur': f"{h.get('price_cur', 0):,.2f}",
            'currency': h.get('currency', 'N/A')
        })

    # 4. Fortress Table
    fortress_display = []
    for h in holdings:
        val = h.get('value_gbp', 0.0)
        weight = (val / total_wealth) if total_wealth > 0 else 0.0
        
        fortress_display.append({
            'ticker': h.get('ticker', 'N/A'),
            'tier': h.get('tier', '2'),
            'weight_current': weight,
            'real_pl': h.get('ppl_gbp', 0.0),
            'action': h.get('action', 'HOLD'), # Auditor should provide this
            'fx_impact': h.get('fx_impact', 0.0),
            'shares': h.get('qty', 0),
            'limit_price': h.get('price_cur', 0), # Fallback to current
            'reason': 'Holding'
        })

    # 5. Sniper List (Mapping keys for template)
    sniper_display = []
    for s in sniper_data:
        sniper_display.append({
            'ticker': s.get('t212_ticker', s.get('ticker', 'N/A')),
            'tier': s.get('tier', '2'),
            'limit_price': s.get('target_price', 0.0), # In Auditor it's target
            'target_weight': s.get('target_weight', 0.05),
            'target_gbp': s.get('target_gbp', 0.0),
            'expected_growth': s.get('expected_growth', 0.0),
            'shares': s.get('shares', 0)
        })

    # 6. Final Template Context
    context = {
        # Header Metrics (Direct mapping)
        'api_total_wealth': total_wealth,
        'api_return_pct': return_pct,
        'api_ppl': total_return,
        'api_cash_free': cash_dry,
        'api_cash_blocked': float(account.get('blocked', 0.0)),
        
        # Heatmap (JSON String for Script)
        'heatmap_data': json.dumps(heatmap_series),
        
        # Tables
        'fortress_holdings': fortress_display,
        'sniper_architect': sniper_display,
        'portfolio_metrics': {
            'cash_balance': cash_dry,
            'total_wealth': total_wealth
        },
        
        # Meta
        'last_update': datetime.now().strftime('%H:%M %d/%m'),
        'version': "v31.1 Platinum"
    }

    # 7. Rendering Logic
    if not os.path.exists(TEMPLATE_FILE):
        print(f"[ARTIST] [ERROR] Template missing: {TEMPLATE_FILE}")
        return

    try:
        with open(TEMPLATE_FILE, 'r', encoding='utf-8') as f:
            template_code = f.read()
            
        template = Template(template_code)
        output_html = template.render(context)
        
        with open(OUTPUT_FILE, 'w', encoding='utf-8') as f:
            f.write(output_html)
            
        print(f"      [SUCCESS] Dashboard written to {OUTPUT_FILE} ({len(output_html)} bytes)")
        
    except Exception as e:
        print(f"      [ERROR] Rendering Failed: {e}")

if __name__ == "__main__":
    # Check if data directory exists
    if not os.path.exists("data"):
        os.makedirs("data")
    render()
