"""
The Artist (Job B) - v31.2 Platinum
The Renderer for Sovereign Sentinel.
STRICT RULE: NO NETWORK CALLS.
Reads live_state.json and generates index.html.
"""

import json
import os
import sys
import math
from datetime import datetime
from jinja2 import Template
from utils import truncate_decimal, format_gbp_truncate, format_pct_truncate

# ==============================================================================
# CONFIGURATION
# ==============================================================================
STATE_FILE = "live_state.json"
TEMPLATE_FILE = "templates/base.html"
OUTPUT_FILE = "index.html"

def load_state():
    """Reads the Live State snapshot generated by Job A."""
    if not os.path.exists(STATE_FILE):
        print(f"[ARTIST] [ERROR] State file {STATE_FILE} not found. please run the Auditor (Job A) first.")
        return None
        
    try:
        with open(STATE_FILE, 'r') as f:
            return json.load(f)
    except Exception as e:
        print(f"[ARTIST] [ERROR] Could not read state file: {e}")
        return None

def safe_val(val, default=0.0):
    if val is None: return default
    try:
        f = float(val)
        if math.isnan(f): return default
        return f
    except:
        return default

def format_gbp(val):
    """Legacy function - use format_gbp_truncate for new code."""
    return format_gbp_truncate(val)

# v32.5: Oracle Ring Engine
def generate_oracle_ring(holdings):
    if not holdings: return ""
    
    
    # Sort: Largest first for geometry
    sorted_holdings = sorted(holdings, key=lambda x: x.get('Value_GBP', x.get('Value', 0)), reverse=True)
    
    radius = 70
    circum = 2 * math.pi * radius
    cumulative_offset = 0 # This tracks the total % used so far
    svg_slices = []
    # Vibrant Palette
    colors = ["#4f46e5", "#10b981", "#ef4444", "#f59e0b", "#8b5cf6", "#ec4899", "#06b6d4"]

    for i, h in enumerate(sorted_holdings):
        val = h.get('Value_GBP', h.get('Value', 0))
        weight = h.get('Weight_Pct', h.get('Weight', 0))
        
        # Filter dust (< 0.1%)
        if weight < 0.1: continue
        
        color = colors[i % len(colors)]
        dash_len = (weight / 100) * circum
        
        # Tooltip content
        name = h.get('Name', h.get('Ticker', 'Asset'))
        val_fmt = f"£{val:,.2f}" # Pre-formatted string
        pct_fmt = f"{weight:.1f}%"
        
        # Safe string escaping for JS
        safe_name = name.replace("'", "\\'")
        
        # v32.7: Sovereign Guard Tooltip (No Math in JS)
        svg_slices.append(f"""
            <circle r="{radius}" cx="100" cy="100" fill="transparent"
                stroke="{color}" stroke-width="22"
                stroke-dasharray="{dash_len} {circum}"
                stroke-dashoffset="-{cumulative_offset}" 
                transform="rotate(-90 100 100)"
                class="donut-segment"
                onmouseover="showTT('{safe_name}', '{val_fmt}', '{pct_fmt}', '{color}')"
                onmouseout="hideTT()"
                style="cursor: pointer; transition: all 0.3s;"></circle>
        """)
        cumulative_offset += dash_len # Move the starting line for the next slice

    return f"""
    <svg viewBox="0 0 200 200" class="w-full h-full">
        <circle cx="100" cy="100" r="{radius}" stroke="#f3f4f6" stroke-width="20" fill="none" />
        {''.join(svg_slices)}
        <text x="100" y="95" text-anchor="middle" class="text-[0.5rem] font-bold fill-gray-400">TOTAL</text>
        <text x="100" y="110" text-anchor="middle" class="text-[0.6rem] font-bold fill-gray-900">ASSETS</text>
    </svg>
    """

def render():
    print(f"Starting The Artist (Job B) [v32.7 Platinum]... ({datetime.now().strftime('%H:%M:%S')})")
    
    # 1. Load Data
    state = load_state()
    if not state:
        sys.exit(1)
        
    meta = state.get('meta', {})
    holdings = state.get('holdings', [])
    sniper_raw = state.get('sniper', [])
    account = state.get('account', {})
    
    print(f"      [DATA] Snapshot Timestamp: {meta.get('timestamp', 'N/A')}")
    print(f"      [DATA] Processing {len(holdings)} holdings.")

    # 2. Extract Metrics
    total_wealth = safe_val(account.get('totalValue', account.get('total', 0.0)))
    
    cash_data = account.get('cash', {})
    if isinstance(cash_data, dict):
        cash_dry = safe_val(cash_data.get('availableToTrade'))
        blocked = safe_val(cash_data.get('reservedForOrders'))
    else:
        cash_dry = safe_val(account.get('free'))
        blocked = safe_val(account.get('blocked'))
        
    invest_data = account.get('investments', {})
    if isinstance(invest_data, dict):
        # v31.2: Fix Total Return = Realized + Unrealized P/L
        realized_pl = safe_val(invest_data.get('realizedProfitLoss'))
        unrealized_pl = safe_val(invest_data.get('unrealizedProfitLoss'))
        total_return = realized_pl + unrealized_pl
        total_cost = safe_val(invest_data.get('totalCost'))
    else:
        total_return = safe_val(account.get('ppl'))
        total_cost = safe_val(account.get('invested'))
    
    # v31.2: Calculate rate of return with truncation
    return_rate_pct = 0.0
    if total_cost > 0:
        return_rate_pct = truncate_decimal((total_return / total_cost) * 100, 2)

    # 3. Heatmap Data
    heatmap_series = []
    for h in holdings:
        val = safe_val(h.get('Value_GBP', h.get('Value', 0)))
        pnl = safe_val(h.get('PL_GBP', h.get('PL', 0)))
        
        invested_val = val - pnl
        pct = (pnl / invested_val) if invested_val > 0 else 0.0
        
        # v32.7: Sovereign Guard Keys
        heatmap_series.append({
            'x': h.get('Ticker', 'N/A'),
            'y': truncate_decimal(val, 2),
            'val_pct': truncate_decimal(pct, 4),
            'company_name': h.get('Name', h.get('Ticker', 'N/A')),
            'shares_held': f"{truncate_decimal(safe_val(h.get('Shares')), 4):,.4f}",
            'formatted_value': f"£{val:,.2f}", # Pre-formatted
            'formatted_pl_gbp': f"{'+' if pnl >= 0 else ''}£{abs(pnl):,.2f}",
            'formatted_pl_pct': f"({pct*100:+.2f}%)",
            'price_avg': truncate_decimal(safe_val(h.get('Avg_Price')), 2),
            'price_cur': f"£{safe_val(h.get('Price_GBP', h.get('Price', 0))):,.2f}",
            'currency': 'GBP', # Normalized
            'pl_per_share_gbp': 0, # Legacy placeholder or calc if needed
            'pl_per_share_pct': 0
        })

    # 4. Fortress Table
    fortress_display = []
    for h in holdings:
        val = safe_val(h.get('Value'))
        pnl = safe_val(h.get('PL'))
        weight = (val / total_wealth) if total_wealth > 0 else 0.0
        
        tier = h.get('Tier', '2')
        target_weight = 0.08 if tier in ['1+', '1'] else 0.05
        
        fortress_display.append({
            'ticker': h.get('Ticker', 'N/A'),
            'company': h.get('Name', h.get('Ticker', 'N/A')), # v32.4 Key Fix
            'book_cost': truncate_decimal(val - pnl, 2),
            'tier': tier,
            'weight_current': truncate_decimal(safe_val(h.get('Weight')) / 100.0, 4) if 'Weight' in h else truncate_decimal(weight, 4), # v32.5
            'weight_target': truncate_decimal(target_weight, 4),
            'real_pl': truncate_decimal(pnl, 2),
            'action': 'HOLD', 
            'fx_impact': truncate_decimal(safe_val(h.get('FX_Impact')), 2),
            'qell_rating': 'PASS',
            'qell_score': 5,
            'shares': truncate_decimal(safe_val(h.get('Shares')), 4),
            'limit_price': truncate_decimal(safe_val(h.get('Price')), 2),
            'reason': 'Holding'
        })

    # 5. Sniper List
    sniper_display = []
    for s in sniper_raw:
        dist = safe_val(s.get('distance_pct'))
        # v32.5: Ensure Intel Fields are passed
        snippet = s.get('hypothesis', s.get('default_thesis', 'No intelligence available.'))
        src = s.get('source', 'System Default')
        
        sniper_display.append({
            'ticker': s.get('t212_ticker', s.get('ticker', 'N/A')),
            'name': s.get('name', 'N/A'),
            'target_price': truncate_decimal(safe_val(s.get('target_price')), 2),
            'current_price': truncate_decimal(safe_val(s.get('live_price')), 2),
            'distance_pct': truncate_decimal(dist, 2),
            'expected_growth_pct': truncate_decimal(safe_val(s.get('expected_growth')), 2),
            'sector': 'Technology',
            'industry': 'Software',
            'priority_score': 15 if dist < 5 else 5,
            'status': s.get('status', 'WATCH'),
            'last_updated': datetime.now().strftime('%H:%M'),
            'is_buy_signal': s.get('status') == 'BUY NOW',
            'hypothesis': snippet,
            'source': src,
            # For sniper_architect block
            'tier': s.get('tier', '2'),
            'limit_price': truncate_decimal(safe_val(s.get('target_price')), 2),
            'target_weight': truncate_decimal(0.05, 4),
            'target_gbp': truncate_decimal(total_wealth * 0.05, 2),
            'expected_growth': truncate_decimal(safe_val(s.get('expected_growth')) / 100.0, 4),
            'shares': int((total_wealth * 0.05) / safe_val(s.get('target_price'))) if safe_val(s.get('target_price')) > 0 else 0
        })

    # 6. Final Template Context
    now = datetime.now()
    tax_end = datetime(now.year + (1 if now.month > 4 or (now.month == 4 and now.day > 5) else 0), 4, 5)
    days_to_tax = (tax_end - now).days

    # v32.5: Generate Oracle Ring
    donut_chart_svg = generate_oracle_ring(holdings)

    # v31.6 Account History Loading
    history_log = []
    log_path = "data/history_log.json"
    if os.path.exists(log_path):
        try:
            with open(log_path, 'r') as f:
                history_log = json.load(f)
                history_log.sort(key=lambda x: x[0])
        except Exception as e:
            print(f"      [WARN] History log load failed: {e}")

    context = {
        'version': "v32.7 Platinum",
        'last_update': datetime.now().strftime('%H:%M %d/%m'),
        'total_wealth_str': format_gbp_truncate(total_wealth),
        'total_return_str': f"{'+' if total_return >= 0 else ''}{format_gbp_truncate(total_return)}",
        'return_pct_str': f"{return_rate_pct:+.2f}%",
        'cash_dry_str': format_gbp_truncate(cash_dry),
        'available_dry_str': format_gbp_truncate(cash_dry),
        'pending_cash_str': format_gbp_truncate(blocked),
        'env': meta.get('env', 'LIVE'),
        'allocation_donut': donut_chart_svg,
        'holdings': holdings,
        'fortress_holdings': fortress_display,
        'sniper_architect': sniper_display,
        'heatmap_dataset': json.dumps(heatmap_series),
        'account_history': json.dumps(history_log),
        'pending_orders': [],
        'portfolio_metrics': {
            'cash_balance': cash_dry,
            'total_wealth': total_wealth,
            'cash_hurdle': 0.038
        },
        'solar': {
            'phase': 'STABLE',
            'tax': {
                'Limit Sentinel': 'Locked',
                'Days to April 5': str(days_to_tax),
                'Loss Harvesting': 'N/A (Tax Free)',
                'Bed & Breakfast': 'Clear'
            }
        }
    }

    # 7. Rendering Logic
    if not os.path.exists(TEMPLATE_FILE):
        print(f"[ARTIST] [ERROR] Template missing: {TEMPLATE_FILE}")
        return

    try:
        with open(TEMPLATE_FILE, 'r', encoding='utf-8') as f:
            template_code = f.read()
            
        template = Template(template_code)
        output_html = template.render(context)
        
        with open(OUTPUT_FILE, 'w', encoding='utf-8') as f:
            f.write(output_html)
            
        print(f"      [SUCCESS] Dashboard written to {OUTPUT_FILE} ({len(output_html)} bytes)")
        
    except Exception as e:
        print(f"      [ERROR] Rendering Failed: {e}")

if __name__ == "__main__":
    render()
