
import os
import json
import datetime
import requests

# 1. NOTIFICATION TEST
TELEGRAM_TOKEN = os.getenv('TELEGRAM_TOKEN', '')
TELEGRAM_CHAT_ID = os.getenv('TELEGRAM_CHAT_ID', '')

print("--- CLOUD CONNECTIVITY TEST ---")
if TELEGRAM_TOKEN and TELEGRAM_CHAT_ID:
    try:
        msg = "☁️ <b>CLOUD TEST INITIATED</b>\n\nVerifying communications and dashboard write capabilities..."
        url = f"https://api.telegram.org/bot{TELEGRAM_TOKEN}/sendMessage"
        requests.post(url, json={'chat_id': TELEGRAM_CHAT_ID, 'text': msg, 'parse_mode': 'HTML'})
        print("✅ Telegram Sent")
    except Exception as e:
        print(f"❌ Telegram Error: {e}")
else:
    print("⚠️ Telegram Credentials Empty")

# 2. DATA UPDATE TEST (Modify ORB Intel)
# This proves the cloud runner can modify data -> which updates dashboard
timestamp = datetime.datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S")

test_intel = {
    "timestamp": timestamp,
    "briefing": f"<h3>CLOUD SYSTEM VERIFIED</h3><p>This message was generated by a remote GitHub Action at <b>{timestamp} GMT</b>.</p><p>It confirms that:</p><ul><li>✅ Cloud Runner is Active</li><li>✅ Notifications are Connected</li><li>✅ Dashboard is Auto-Updating</li></ul><p><b>System is GREEN for Autonomous Operations.</b></p>",
    "targets": []
}

os.makedirs("data", exist_ok=True)
with open("data/orb_intel.json", "w") as f:
    json.dump(test_intel, f, indent=4)
    
print("✅ data/orb_intel.json updated with Test Message")
