import json
with open('live_state.json', 'r') as f:
    state = json.load(f)
    holdings = state.get('holdings', [])
    sum_pl = sum(h.get('PL_GBP', 0) for h in holdings)
    total_gbp = state.get('total_gbp', 0)
    acc = state.get('account', {})
    inv = acc.get('investments', {})
    realized = inv.get('realizedProfitLoss', 0)
    print("--- VERIFICATION ---")
    print(f"Sum PL: {sum_pl}")
    print(f"Realized: {realized}")
    print(f"Total Return: {sum_pl + realized}")
    tw = total_gbp + acc.get('cash', {}).get('availableToTrade', 0) + acc.get('cash', {}).get('reservedForOrders', 0)
    print(f"Total Wealth: {tw}")
